baseURL = 'https://haoolii.github.io/'
languageCode = 'zh-CN'
title = 'Haoolii Note'
theme = 'hugo-paper'
author = "haoolii"
copyright = "Copyright © 2008–2024, Steve Francia and the haoolii; all rights reserved."
paginate = 3

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10